GSM-MSG/MSG-BackEnd-V2

package-lock.json
package.json
src/Entities/User.entity.ts

Add User Entity

---

src/Entities/Club.entity.ts
src/Entities/Member.entity.ts
src/Entities/User.entity.ts

Add Member Table

---

src/Entities/Club.entity.ts
src/Entities/Member.entity.ts
src/Entities/RelatedLink.entity.ts
src/Entities/RequestJoin.entity.ts
src/Entities/User.entity.ts
src/Entities/index.ts
src/app.module.ts

Typeorm 수정

---

src/Entities/User.entity.ts

Update User Entity

---

src/Entities/User.entity.ts

Update user entity refreshToken

---

.gitignore
src/auth/auth.controller.ts
src/auth/auth.service.ts
src/main.ts

- isVerify bug 수정
- head 메서드에서 body 말고 queryString으로 받기

Update auth bug

---

src/Entities/Club.entity.ts

EditClubEntity

---

src/app.module.ts
src/user/user.controller.spec.ts
src/user/user.controller.ts
src/user/user.module.ts
src/user/user.service.spec.ts
src/user/user.service.ts

user controller,module,service를 만들었습니다

Add user folder

---

src/Entities/Club.entity.ts
src/Entities/RelatedLink.entity.ts
src/user/user.controller.ts
src/user/user.service.ts

🔀 User/search

---

src/user/dto/exit.dto.ts
src/user/user.controller.ts
src/user/user.service.ts

🔀  User/exit

---

src/Entities/Club.entity.ts
src/Entities/RelatedLink.entity.ts

:poop: entity 관계 변경

---

src/strategies/atStrategy.ts
src/strategies/rtStrategy.ts

> 보안을 강화했습니다
> 중요한 부분이니 제가 잘못한 거 없는지 잘 확인해 주세요

Update at & rt strategy

---

package-lock.json
package.json
src/auth/auth.service.ts
src/email/email.service.ts

🔀 Update emailService

---

src/Club/club.controller.ts
src/Club/club.service.ts
src/Club/dto/editclub.dto.ts

에러처리를 했습니다. 에러처리보다 변수변경이 더 많습니다.

Errorhandling

---

src/Club/club.controller.ts
src/Club/club.service.ts
src/app.module.ts
src/email/email.service.ts
src/user/user.controller.ts
src/user/user.service.ts

🐛 Update dto

---

src/Club/club.service.ts

:bug: 상세페이지 오류

---

src/image/image.service.ts

🐛 Update imageService

---

src/user/user.controller.ts
src/user/user.service.ts

🔀 오류 수정 + 쿼리 이름이상한거 수정

---

src/auth/auth.service.ts

🔀 15분이 빠지는게아닌 추가되서 반환

---

src/Club/club.service.ts

:bug: 변수명 변경

---

.eslintrc.js

> 윈도우 개발자의 고통이 담긴 pr입니다 ㅠㅠ
[관련 자료](https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-delete-cr-prettier-prettier)

🔀 Update eslint

---

src/Club/club.service.ts
src/strategies/atStrategy.ts
src/user/user.service.ts

> 앞으로는 typeorm에서 find를 할 때 where을 반드시 작성해 줘야 하는 것 같습니다

🔀 typeorm update error

---

src/image/image.web.controller.ts

:beers: 술 한잔 먹었습니다.

---

src/Club/club.controller.ts
src/Club/club.service.ts
src/Club/club.web.controller.ts
src/user/user.controller.ts
src/user/user.service.ts
src/user/user.web.controller.ts

대소문자를 실수하면 docker build가 안 돼요 ㅠㅠ

🐛 대소문자 실수 해결

---

Dockerfile
src/auth/auth.service.ts
src/strategies/rtStrategy.ts

🐛 Update 여러가지 실수

---

src/app.module.ts
src/lib/logger.middleware.ts

🔀 Add global logger

---

src/Club/club.service.ts

:sparkles: 동아리 생성할때 isOpened변수 추가

---

src/Club/club.controller.ts
src/Club/club.service.ts
src/Club/club.web.controller.ts
src/Club/dto/ClubData.dto.ts
src/Club/dto/ClubUser.dto.ts
src/Club/dto/createClub.dto.ts
src/Club/dto/editclub.dto.ts
src/Entities/Club.entity.ts
src/Entities/index.ts
src/app.module.ts
src/auth/auth.controller.ts
src/auth/auth.service.ts
src/auth/dto/index.ts
src/image/image.service.ts
src/user/user.controller.ts
src/user/user.service.ts
src/user/user.web.controller.ts

:memo: 파일 대소문자

---

src/auth/auth.controller.ts
src/auth/auth.service.ts
src/strategies/rtStrategy.ts

🔒️ Update refresh service, controller

---

src/Club/club.service.ts

:bug: 동아리 리스트 멤버 500오류

---

src/Club/club.service.ts

:fire: log삭제ㅎㅎ

---

src/Club/club.service.ts

:zap: return값 개선

---

src/Entities/AfterSchool.entity.ts

:sparkles: 동아리 오픈여부

---

src/auth/auth.service.ts
src/auth/auth.web.controller.ts

🔀 gsm user 처리 추가

---

src/auth/auth.web.controller.ts

🔀 Update web app 겹침 현상 제거

---

src/auth/auth.web.controller.ts

🐛 Update 로그아웃 오류

---

src/image/image.web.controller.ts

> web img 업로드 url 변경
> `/img` -> `/img/web`

🐛 Update 웹과 모바일 url 겹침 제거

---

src/Club/club.service.ts
src/auth/auth.web.controller.ts
src/strategies/rtStrategy.ts

🐛 Update kickUser.dto -> kickuser.dto

---

src/auth/auth.service.ts

대충 리팩토링이라는 뜻. 
where에 : 안붙여도 되는거 생략
findStudent()할때 불필요한 문자열 보간 제거

🔀 :: auth.service부분 일부 코드 리팩토링

---

src/auth/auth.service.ts

🔀 client id 추가

---

src/Entities/AfterSchool.entity.ts

:fire: 수요조사로 변경되면서 entity 수정

---

src/Club/club.service.ts

- findMember의 return type과 application의 return type을 비슷하게 맞췄습니다
- 추가로  리팩터링

📝 Update findeMember return type

---

src/Club/dto/createClub.dto.ts
src/Club/dto/editclub.dto.ts

createClubdto와 editClubDto에 contact부분에 notempty추가

:memo: contact추가

---

src/Club/club.controller.ts
src/user/user.controller.ts
src/user/user.service.ts
src/user/user.web.controller.ts

유저 검색에서 검색하는 본인도 검색결과에 나오는 것을 고쳤습니다

🔀 자기 자신도 검색되는거 수정

---

src/Club/club.service.ts

상세페이지에 다른 동아리에 소속되어있거나 동아리 신청을 넣은 유저에게 other로 반환하는 로직을 구현하였습니다.

:sparkles: detailPage에 OTHER추가

---

src/Club/club.service.ts

상세페이지에 활동사진 url변수를 카멜표기법으로 변경하였습니다.
---

:recycle: detailPage변수

---

src/Entities/Teacher.entity.ts

어드민서버와 DB테이블 통일화 진행
-선생님 엔티티 추가

🔀 선생님 엔티티 추가

---

src/Club/club.service.ts

:bug: 방과후 신청

---

src/Club/club.service.ts
src/guest/guest.service.ts

#178 동아리 생성 시 사진 저장이 안됌
* 클럽 생성할때 이미지 저장
* guest부분에서 변수 변경
최형우 죽어....

:sparkles: 이미지 저장

---

src/Club/club.service.ts

🔀 부장위임 파트 리팩토링

---

src/Club/club.service.ts

클럽생성 중 추가한 멤버가 잘못되면 삭제되는 로직을 추가하였습니다.

:sparkles: 예외처리

---

src/Entities/AfterSchool.entity.ts
src/Entities/ClassRegistration.entity.ts

🔀 지금 필요없는 컬럼 삭제

---

src/Club/club.controller.ts
src/Entities/ClassRegistration.entity.ts

🔀 Nest의 기본 테이블이름은 스네이크표기법입니다

---

src/Club/club.service.ts

다른 동아리에 소속되어 있는 유저 또한 other로 리턴하는 것을 수정하였습니다.
동아리 생성에 멤버 추가 로직의 statuscode가 수정되었습니다.

detail에 userScope중 other의 조건을 수정

---

src/Entities/AfterSchool.entity.ts

필요없는 canDuplicate 삭제
+
isOpened랑 yearOf의 컬럼명을 카멜마운트로 고정하였습니다

🔀 컬럼이름 수정 및 필요없는 컬럼삭제

---

src/Club/club.service.ts
src/Entities/image.entity.ts

동아리에 멤버가 없을 때 삭제되는 로직을 실행 중 이미지가 없으면 500이 뜨는 버그 해결
이미지 entity타입 변경

:bug: 디테일 버그

---

src/user/user.service.ts

🔀 Edit/throw

---

src/Club/club.service.ts
src/image/image.service.ts

#192 동아리에 같은 인원이 중복으로 들어가요
#191 동아리 생성할 때 이미지가 4개를 초과하는 버그

동아리 생성 할 때 인원이 중복으로 들어가는 버그

---

src/Club/club.service.ts

상세페이지에 가면 사설동아리에 가입되지도 않았는데 other로 출력되는 문제 해결

상세페이지 scope 문제
